version: "3"
services:
  app:
    env_file:
      - .env
    container_name: ijaz_nest_bp
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_bp
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
